--SETUP SERVER AUDIT with DATABASE AUDIT SPECS

USE [master]

CREATE SERVER AUDIT [audit_epacresolve_guest]
TO FILE 
(	FILEPATH = N'E:\Audit\'
	,MAXSIZE = 64 MB
	,MAX_ROLLOVER_FILES = 10
	,RESERVE_DISK_SPACE = OFF
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
)
WHERE ([Database_Principal_Name] = 'guest')

ALTER SERVER AUDIT [audit_epacresolve_guest] WITH (STATE = OFF)
GO


USE [EPACRESOLVE]

CREATE DATABASE AUDIT SPECIFICATION [auditspecs_epacresolve_guest]
FOR SERVER AUDIT [audit_epacresolve_guest]
ADD (SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP),
ADD (DATABASE_LOGOUT_GROUP),
ADD (DATABASE_OBJECT_ACCESS_GROUP),
ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP),
ADD (FAILED_DATABASE_AUTHENTICATION_GROUP),
ADD (SCHEMA_OBJECT_ACCESS_GROUP)
WITH (STATE = OFF)
GO

USE [master]
ALTER SERVER AUDIT [audit_epacresolve_guest] WITH (STATE = ON)

USE [EPACRESOLVE]
ALTER DATABASE AUDIT SPECIFICATION [auditspecs_epacresolve_guest] WITH (STATE = ON)
GO